config/routes.rb
Nubeporra::Application.routes.draw do

  resources :boxings do
    member do
      get 'standing'
    end
  end

  devise_for :users

  resources :games do
    resources :bets
  end

  resources :scoretypes do
    resources :scoretypevalues
  end

  root :to =>            'static_pages#home'

  match '/home',     to: 'static_pages#home'

  match '/users/:id/bets',  to: 'bets#user'

  match '/football/:date/matchsday',  to: 'footballscoreapi#matchsday'

 

end

app/models/boxing.rb
class Boxing < ActiveRecord::Base
  has_many :games

  attr_accessible :description

 def numpoints(user)
    points = 0
    self.games.each do |game|
    	bet = game.userbet(user)
    	(points += bet.totalpoints) if bet
    end
    points
  end

end

app/controllers/boxings_controller.rb
class BoxingsController < ApplicationController
  # GET /boxings
  # GET /boxings.json
  def index
    @boxings = Boxing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxings }
    end
  end

  def standing
    @boxing = Boxing.find(params[:id])
    @standings = User.all.sort_by { |user| (@boxing.numpoints user) * -1}
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @boxing }
    end
  end

  # GET /boxings/1
  # GET /boxings/1.json
  def show
    @boxing = Boxing.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @boxing }
    end
  end

  # GET /boxings/new
  # GET /boxings/new.json
  def new
    @boxing = Boxing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @boxing }
    end
  end

  # GET /boxings/1/edit
  def edit
    @boxing = Boxing.find(params[:id])
  end

  # POST /boxings
  # POST /boxings.json
  def create
    @boxing = Boxing.new(params[:boxing])

    respond_to do |format|
      if @boxing.save
        format.html { redirect_to @boxing, notice: 'Boxing was successfully created.' }
        format.json { render json: @boxing, status: :created, location: @boxing }
      else
        format.html { render action: "new" }
        format.json { render json: @boxing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxings/1
  # PUT /boxings/1.json
  def update
    @boxing = Boxing.find(params[:id])

    respond_to do |format|
      if @boxing.update_attributes(params[:boxing])
        format.html { redirect_to @boxing, notice: 'Boxing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @boxing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxings/1
  # DELETE /boxings/1.json
  def destroy
    @boxing = Boxing.find(params[:id])
    @boxing.destroy

    respond_to do |format|
      format.html { redirect_to boxings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/boxings_helper.rb
module BoxingsHelper
end

app/views/boxings/_form.html.erb
<%= form_for @boxing, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                boxings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/boxings/edit.html.erb
<%- model_class = Boxing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/boxings/index.html.erb
<%- model_class = Boxing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @boxings.each do |boxing| %>
      <tr>
        <td><%= link_to boxing.id, boxing_path(boxing) %></td>
        <td><%= boxing.description %></td>
        <td><%=l boxing.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_boxing_path(boxing), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      boxing_path(boxing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_boxing_path,
            :class => 'btn btn-primary' %>

app/views/boxings/new.html.erb
<%- model_class = Boxing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/boxings/show.html.erb
<%- model_class = Boxing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @boxing.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              boxing_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_boxing_path(@boxing), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              boxing_path(@boxing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/boxings/standing.html.erb
<%- model_class = Boxing -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  <h2><%= @boxing.description %></h2>
</div>

<div class="row">
  <div class="span4">
    <table class="table table-striped table-condensed table-bordered">
      <thead>
        <tr>
          <th>Jugador</th>
          <th>Punts Boxing</th>
          <th>Punts</th>
        </tr>
      </thead>
      <tbody>
        <% @standings.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= @boxing.numpoints(user) %></td>
          <td><%= user.numpoints %></td>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              home_path, :class => 'btn'  %>
</div>