config/routes.rb
Nubeporra::Application.routes.draw do

  resources :boxings do
    member do
      get 'standing'
    end
  end

  devise_for :users

  resources :games do
    resources :bets
  end

  resources :scoretypes do
    resources :scoretypevalues
  end

  root :to =>            'static_pages#home'

  match '/home',     to: 'static_pages#home'

  match '/users/:id/bets',  to: 'bets#user'

  match '/football/:date/matchsday',  to: 'footballscoreapi#matchsday'

 

end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :boxing 
  has_many :bets
 
  attr_accessible :closeTime, :description, :gameTime, :score1, :score2, :score3, :typescore, :numscore, :numpoint, :closed, :boxing_id, :secondpoint

  def userbet(user)
  	self.bets.where(:user_id => user).first
  end

  def score
  	score = self.score1 if self.score1
  	if self.numscore >= 2
      score += (' - ' + self.score2) if self.score2
    end
  	if self.numscore >= 3
      score += (' - ' + self.score3) if self.score3
    end
    score    
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!
  # GET /games
  # GET /games.json
  def index
#    @games = Game.all
    @games = Game.order('"gameTime"').where(:gameTime => 5.days.ago..60.days.from_now)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for @game, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :closed, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :closed %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :typescore, :class => 'control-label' %>
    <div class="controls">
      <%= select(:game, :typescore, Settings.typeScore, options={:class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :numpoint, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :numpoint, :class => 'text_field' %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :secondpoint, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :secondpoint, :class => 'text_field' %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :numscore, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :numscore, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :boxing_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :score1, :class => 'control-label' %>
    <div class="controls">
      <%= select(:game, :score1, Settings[@game.typescore], options={:include_blank => true, :class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :score2, :class => 'control-label' %>
    <div class="controls">
      <%= select(:game, :score2, Settings[@game.typescore], options={:include_blank => true, :class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :score3, :class => 'control-label' %>
    <div class="controls">
      <%= select(:game, :score3, Settings[@game.typescore], options={:include_blank => true, :class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :closeTime, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :closeTime, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gameTime, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :gameTime, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                games_path, :class => 'btn' %>
  </div>
<% end %>

app/views/games/_formNew.html.erb
<%= form_for @game, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :typescore, :class => 'control-label' %>
    <div class="controls">
      <%= select(:game, :typescore, Settings.typeScore, options={:class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :numpoint, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :numpoint, :class => 'text_field' %>
    </div>
  <div class="control-group">
    <%= f.label :secondpoint, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :secondpoint, :class => 'text_field' %>
    </div>
  </div>
  </div>  
  <div class="control-group">
    <%= f.label :numscore, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :numscore, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :boxing_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:game, :boxing_id, Boxing.all, :id, :description, options={:include_blank => true, :class => "selectpicker"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :closeTime, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :closeTime, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gameTime, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :gameTime, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                games_path, :class => 'btn' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/games/index.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:typescore) %></th>
      <th><%= model_class.human_attribute_name(:closeTime) %></th>
      <th><%= model_class.human_attribute_name(:gameTime) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.id, game_path(game) %></td>
        <td><%= game.description %></td>
        <td><%= game.typescore %></td>
        <td><%= game.closeTime %></td>
        <td><%= game.gameTime %></td>
        <td><%=l game.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_game_path(game), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      game_path(game),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_game_path,
            :class => 'btn btn-primary' %>

app/views/games/new.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'formNew' %>

app/views/games/show.html.erb
<%- model_class = Game -%>
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @game.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:score1) %>:</strong></dt>
  <dd><%= @game.score1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:score2) %>:</strong></dt>
  <dd><%= @game.score2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:score3) %>:</strong></dt>
  <dd><%= @game.score3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:closeTime) %>:</strong></dt>
  <dd><%= @game.closeTime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gameTime) %>:</strong></dt>
  <dd><%= @game.gameTime %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              games_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_game_path(@game), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              game_path(@game),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>