config/routes.rb
Nubeporra::Application.routes.draw do

  resources :boxings do
    member do
      get 'standing'
    end
  end

  devise_for :users

  resources :games do
    resources :bets
  end

  resources :scoretypes do
    resources :scoretypevalues
  end

  root :to =>            'static_pages#home'

  match '/home',     to: 'static_pages#home'

  match '/users/:id/bets',  to: 'bets#user'

  match '/football/:date/matchsday',  to: 'footballscoreapi#matchsday'

 

end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nubeporra</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">NubePorra</a>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><a href="#">Estas logat com <%= current_user.email %></a></li>
            <% end %>  
            <li><%= link_to "Inici", home_path  %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accions<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Boxing", boxings_path  %></li>
                <li><%= link_to "Partits", games_path  %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuari<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                <li><%= link_to "Canvia detalls", edit_user_registration_path  %></li>
                <li><%= link_to "Tanca sessio", destroy_user_session_path, :method => :delete %></li>
                <% else %>
                <li><%= link_to "Registra't", new_user_registration_path %></li>
                <li><%= link_to "Inicia sessio", new_user_session_path %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= render 'layouts/flash_messages' %>  
    <%= yield %>
  </div>

</body>
</html>